// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.6
// source: suggest_username.proto

package requestparser

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SuggestUsernameRequest struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Username      *SuggestUsernameRequest_NameWrapper `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`                                 // Field 1: username
	Locale        string                              `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`                                     // Field 2: locale (empty string)
	SomethingFlag uint32                              `protobuf:"varint,3,opt,name=something_flag,json=somethingFlag,proto3" json:"something_flag,omitempty"` // Field 3: something flag (0 is off)
	DeviceId      string                              `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`                 // Field 4: device ID (UUID)
	SessionId     string                              `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`              // Field 5: session ID (UUID)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestUsernameRequest) Reset() {
	*x = SuggestUsernameRequest{}
	mi := &file_suggest_username_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestUsernameRequest) ProtoMessage() {}

func (x *SuggestUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_suggest_username_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestUsernameRequest.ProtoReflect.Descriptor instead.
func (*SuggestUsernameRequest) Descriptor() ([]byte, []int) {
	return file_suggest_username_proto_rawDescGZIP(), []int{0}
}

func (x *SuggestUsernameRequest) GetUsername() *SuggestUsernameRequest_NameWrapper {
	if x != nil {
		return x.Username
	}
	return nil
}

func (x *SuggestUsernameRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *SuggestUsernameRequest) GetSomethingFlag() uint32 {
	if x != nil {
		return x.SomethingFlag
	}
	return 0
}

func (x *SuggestUsernameRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SuggestUsernameRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SuggestUsernameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestions   []string               `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`                     // Field 1: repeated usernames
	SuccessCode   uint32                 `protobuf:"varint,2,opt,name=success_code,json=successCode,proto3" json:"success_code,omitempty"` // Field 2: success code (uint32)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestUsernameResponse) Reset() {
	*x = SuggestUsernameResponse{}
	mi := &file_suggest_username_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestUsernameResponse) ProtoMessage() {}

func (x *SuggestUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_suggest_username_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestUsernameResponse.ProtoReflect.Descriptor instead.
func (*SuggestUsernameResponse) Descriptor() ([]byte, []int) {
	return file_suggest_username_proto_rawDescGZIP(), []int{1}
}

func (x *SuggestUsernameResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

func (x *SuggestUsernameResponse) GetSuccessCode() uint32 {
	if x != nil {
		return x.SuccessCode
	}
	return 0
}

type SuggestUsernameRequest_NameWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Nested message for the username
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestUsernameRequest_NameWrapper) Reset() {
	*x = SuggestUsernameRequest_NameWrapper{}
	mi := &file_suggest_username_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestUsernameRequest_NameWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestUsernameRequest_NameWrapper) ProtoMessage() {}

func (x *SuggestUsernameRequest_NameWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_suggest_username_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestUsernameRequest_NameWrapper.ProtoReflect.Descriptor instead.
func (*SuggestUsernameRequest_NameWrapper) Descriptor() ([]byte, []int) {
	return file_suggest_username_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SuggestUsernameRequest_NameWrapper) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_suggest_username_proto protoreflect.FileDescriptor

const file_suggest_username_proto_rawDesc = "" +
	"\n" +
	"\x16suggest_username.proto\x12\rrequestparser\"\x85\x02\n" +
	"\x16SuggestUsernameRequest\x12M\n" +
	"\busername\x18\x01 \x01(\v21.requestparser.SuggestUsernameRequest.NameWrapperR\busername\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\x12%\n" +
	"\x0esomething_flag\x18\x03 \x01(\rR\rsomethingFlag\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x1a!\n" +
	"\vNameWrapper\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"^\n" +
	"\x17SuggestUsernameResponse\x12 \n" +
	"\vsuggestions\x18\x01 \x03(\tR\vsuggestions\x12!\n" +
	"\fsuccess_code\x18\x02 \x01(\rR\vsuccessCodeB\x17Z\x15modules/requestparserb\x06proto3"

var (
	file_suggest_username_proto_rawDescOnce sync.Once
	file_suggest_username_proto_rawDescData []byte
)

func file_suggest_username_proto_rawDescGZIP() []byte {
	file_suggest_username_proto_rawDescOnce.Do(func() {
		file_suggest_username_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_suggest_username_proto_rawDesc), len(file_suggest_username_proto_rawDesc)))
	})
	return file_suggest_username_proto_rawDescData
}

var file_suggest_username_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_suggest_username_proto_goTypes = []any{
	(*SuggestUsernameRequest)(nil),             // 0: requestparser.SuggestUsernameRequest
	(*SuggestUsernameResponse)(nil),            // 1: requestparser.SuggestUsernameResponse
	(*SuggestUsernameRequest_NameWrapper)(nil), // 2: requestparser.SuggestUsernameRequest.NameWrapper
}
var file_suggest_username_proto_depIdxs = []int32{
	2, // 0: requestparser.SuggestUsernameRequest.username:type_name -> requestparser.SuggestUsernameRequest.NameWrapper
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_suggest_username_proto_init() }
func file_suggest_username_proto_init() {
	if File_suggest_username_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_suggest_username_proto_rawDesc), len(file_suggest_username_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_suggest_username_proto_goTypes,
		DependencyIndexes: file_suggest_username_proto_depIdxs,
		MessageInfos:      file_suggest_username_proto_msgTypes,
	}.Build()
	File_suggest_username_proto = out.File
	file_suggest_username_proto_goTypes = nil
	file_suggest_username_proto_depIdxs = nil
}
